UsersDemo/UserBasic/urls.py
from django.urls import path
from UserBasic import views

#  Template urls

app_name = 'basicapp'

urlpatterns=[
	path('register/',views.register,name='register'),
	path('userlogin/',views.userlogin,name='userlogin')
]

UsersDemo/UsersDemo/urls.py
from django.contrib import admin
from django.urls import path,include
from UserBasic import views

urlpatterns = [
	path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('UserBasic.urls')),
    path('logout/',views.userlogout,name='logout'),
    path('special/',views.special,name='special')
]

UsersDemo/UserBasic/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
	"""docstring for UserProfileInfo"""

	user = models.OneToOneField(User,on_delete=models.DO_NOTHING)


	#  additional

	portfolio_site = models.URLField(blank=True)

	profile_pic = models.ImageField(upload_to='profilePics',blank=True)

	def __str__(self):
		return self.user.username
		pass

UsersDemo/UserBasic/forms.py
from django import forms
from django.contrib.auth.models import User
from UserBasic.models import UserProfileInfo


class UserForm(forms.ModelForm):
	"""docstring for UserForm"""
	password = forms.CharField(widget=forms.PasswordInput())


	class Meta():
		"""docstring for Meta"""
		model = User
		fields = ('username','email','password')

class UserProfileInfoForms(forms.ModelForm):
	"""docstring for UserProfileInfoForms"""
	
	class Meta():
		"""docstring for Meta"""
		model = UserProfileInfo
		fields = ('portfolio_site','profile_pic')
			

UsersDemo/UserBasic/views.py
from django.shortcuts import render
from UserBasic.forms import UserForm,UserProfileInfoForms

# 

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(req):
	return render(req,'userBasic/index.html')

@login_required
def special(req):
	return HttpResponse("Awsome! You are logged in.")


@login_required
def userlogout(req):
	logout(req)
	return HttpResponseRedirect(reverse('index'))


def register(req):
	registereds = False

	if req.method == "POST":
		user_form = UserForm(data=req.POST)
		profile_form = UserProfileInfoForms(data=req.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit=False)
			profile.user = user


			if 'profile_pic' in req.FILES:
				profile.profile_pic = req.FILES['profile_pic']

			profile.save()

			registereds = True

		else:
			print(user_form.errors,profile_form.errors)

	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForms()

	return render(req,'userBasic/registration.html',
								{'user_form':user_form,
								  'profile_form':profile_form,
								   'registered':registereds})

def userlogin(req):
	

	if req.method == 'POST':
		username = req.POST.get('username')
		password = req.POST.get('password')

		user = authenticate(username=username,password=password)

		if user:
			if user.is_active:
				login(req,user)

				return render(req,'userBasic/hello.html',{})
				# return HttpResponseRedirect(reverse('index'))

			else:
				return HttpResponse("ACCOUNT NOT ACTIVE")

		else:
			print("Someone Tried to Login and Failed!!")

			print("Username: {} and password {}".format(username,password))
			return HttpResponse("invalid login credentials!!")

	else:
		return render(req,'userBasic/login.html',{})

UsersDemo/templates/userBasic/base.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html>
<head>
	<title>Base</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
 
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	 
	  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    <div class="navbar-nav">
	      <a class="navbar-brand" href="{% url 'index'  %}">DJANGO</a>
	      <a class="nav-item nav-link" href="{% url 'admin:index'  %}">Admin</a>
	      <a class="nav-item nav-link" href="{% url 'basicapp:register' %}">Register</a>

	      {% if user.is_authenticated %}
	        <li><a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a></li>
	      {% else %}
	      	<li><a class="nav-item nav-link" href="{% url 'basicapp:userlogin' %}">Login</a></li>

	      {% endif %}

	    </div>
	  </div>
	</nav> 

	<div class="container">

		{% block body_block %}

			  
		 {% endblock %}

	 </div> 


</body>
</html>

UsersDemo/templates/userBasic/hello.html
{% extends "userBasic/base.html" %}
{% block body_block %}

<div class="jumbotron">
	<h1>Hello!!</h1>
	<h2>You Have Successfully Logged In..!!</h2>

</div>

{% endblock %}

UsersDemo/templates/userBasic/index.html
{% extends "userBasic/base.html" %}
{% block body_block %}

<div class="jumbotron">
	<h1>DJango level Five</h1>

</div>

{% endblock %}

UsersDemo/templates/userBasic/login.html
{% extends 'userBasic/base.html' %}
{% block body_block %}

<div class="jumbotron">
	<h1>Please Login</h1>
	<form action="{% url 'basicapp:userlogin' %}" method="post">

	{% csrf_token %}
	<label for="username">Username:</label>
	<input type="text" name="username" placeholder="Enter Username">	

	<label for="password">Password:</label>	
	<input type="password" name="password">

	<input type="submit" name="" value="Login">


	</form>


</div>


{% endblock %}

UsersDemo/templates/userBasic/registration.html
{% extends "userBasic/base.html" %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">

	{% if registered %}
	<h1>Thankyou for registering</h1>

	{% else %}

		<h1>Register Here</h1>
		<h3>Fill out the form:</h3>

		<form enctype="multipart/form-data" method="post">
			{% csrf_token %}
			{{ user_form.as_p }}
			{{ profile_form.as_p }}	
			<input type="submit" value="Register">
		</form>

	{% endif %}

</div>

{% endblock %}